Save submitted answers
kellerflint/sql-project-api pull request #6
Opened 2023-11-22 02:05 UTC by JamesM25

2023-11-22 19:07 UTC, kellerflint requested changes
Overall looks great! Error handling is much better. I have some suggestions for data access and the QueryHistory thing we discussed the other day. Ping me when you have changes/questions.

2023-11-22 19:07 UTC, kellerflint commented on src/Index.ts
> +    //console.error(err.stack);
Either uncomment if intended to be part of logging or remove

2023-11-22 19:07 UTC, kellerflint commented on src/service/AssignmentService.ts
> +        // TODO: Make sure there are no duplicates
I'd rather this be recorded as an issue or work item or something than leaving a comment it in the code

2023-11-22 19:07 UTC, kellerflint commented on src/service/AssignmentService.ts
> +        const history = answerSelectResult.rows[0].query_history.split(HISTORY_DELIMITOR);
I think this should be done as a separate QueryHistory table with an FK reference to the answer.

2023-11-22 19:07 UTC, kellerflint commented on src/service/AssignmentService.ts
> +        WHERE ua_id = @ua AND question_id = @question`,
I'm not a fan of writing out SQL in these functions. I think the better apporach would be to use the repository pattern and handle the queries in a separate file that's sole job is to interact with the DB. SQL code should probably not appear in our AssignmentService, it should just be our business logic. Including data access details means we're violating the separation of concerns principle.

Ideally this clearHistory function for example would just look more like this:
clearHistory(...) { 
  const userAssignmentResult = await assignmentRepo.getAssignmentByQuestionId(questionId);
  checkQueryResults(userAssignmenetResult, true);
  const result = await assignmentRepo.setQueryHistory(questionId, uaId)
}

This is much better for other developers working on our code as we're working only at the abstraction level of the business rules. It's nice to only show what they need to know at this level, not to show them all the details of data access they probably don't care about. If they want those details, they can always click into the repo function.

2023-11-27 20:35 UTC, kellerflint submitted a review, later dismissed

2023-11-27 20:35 UTC, kellerflint commented on src/service/AssignmentService.ts
> +const HISTORY_DELIMITOR = '\0';
Is this still necessary?

2023-11-28 00:21 UTC, kellerflint approved these changes, later dismissed
👍

2023-11-28 19:41 UTC, kellerflint approved these changes
👍

2023-11-28 22:34 UTC, jenniferzal approved these changes

2023-11-28 22:47 UTC, merged